#!/usr/bin/python3
import cgi 
import sqlite3 # import librairy pour sqlite  

import time
import uuid # importe librairy pour creation id 
import http.cookies # importe librairy pour creation id
import os 

# Fichier de cookie
SESSION_DIR = "/tmp/session"
os.makedirs(SESSION_DIR, exist_ok=True)

# Créer une instance de cookie
cookie = http.cookies.SimpleCookie(os.environ.get("HTTP_COOKIE"))
session_id = cookie.get("session_id")
new_id = False

# Creation du fichier sqlite3 
base = sqlite3.connect("data/database.sqlite3")
cursor = base.cursor()

# Creation de table sql Users
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        admin INTEGER,
        user VARCHAR(64),
        password VARCHAR(255),
        dt DATETIME DEFAULT CURRENT_TIMESTAMP
    )
""")

# Creation de la table Sessions
#todo verifier la taile ip 
cursor.execute(""" 
    CREATE TABLE IF NOT EXISTS Sessions(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        id_user INTEGER,
        finish INTEGER,
        session VARCHAR(64),
        creation DATETIME DEFAULT CURRENT_TIMESTAMP,
        ip VARCHAR(16),
        FOREIGN KEY (id_user) REFERENCES users(id)
    )
""")

if session_id:
    cursor.execute("SELECT * FROM Users INNER JOIN Sessions ON Users.id = Sessions.id_user WHERE Sessions.session = ?",
    (session_id.value,))
    resulta = cursor.fetchone()
    if resulta : 
        # print("""Content-Type: text/html""")
        # print(f"""
        # <!DOCTYPE html>
        # <html lang="en">
        # <head>
        #     <meta charset="UTF-8">
        #     <meta name="viewport" content="width=device-width, initial-scale=1.0">
        #     <title>Document</title>
        # </head>
        # <body>
        #     <p>{resulta[2]}</p>
        # </body>
        # </html>""")
        # exit()
        pass


cursor.execute("""
    SELECT Posts.id, Posts.titel, Posts.texte, Users.user
    FROM Posts
    INNER JOIN Users ON Posts.id_user = Users.id
""")
rows = cursor.fetchall()

add = ""
for post in rows:
    post_id, titre, texte, auteur = post
    add += f"""
    <div>
        <h3>{titre}</h3>
        <a href='post?id_post={post_id}'>{texte}</a>
        <p>Auteur : {auteur}</p>
    </div>
    """

    
print("""Content-Type: text/html""")
print(f"""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <p>{add}</p>
</body>
</html>
""")