#!/usr/bin/python3

import cgi 
import sqlite3 # import librairy pour sqlite  
import hashlib # importe librairy pour hashage 

import time
import uuid # importe librairy pour creation id 
import http.cookies # importe librairy pour creation id
import os 

# Fichier de cookie
SESSION_DIR = "/tmp/session"
os.makedirs(SESSION_DIR, exist_ok=True)

# Créer une instance de cookie
cookie = http.cookies.SimpleCookie(os.environ.get("HTTP_COOKIE"))
session_id = cookie.get("session_id")
new_id = False

# Creation du fichier sqlite3 
base = sqlite3.connect("data/database.sqlite3")
cursor = base.cursor()

# Creation de table sql Users
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Users (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        admin INTEGER,
        user VARCHAR(64),
        password VARCHAR(255),
        dt DATETIME DEFAULT CURRENT_TIMESTAMP
    )
""")

# Creation de la table Sessions
cursor.execute("""
    CREATE TABLE IF NOT EXISTS Sessions(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        id_user INTEGER,
        finish INTEGER,
        session VARCHAR(64),
        creation DATETIME DEFAULT CURRENT_TIMESTAMP,
        ip VARCHAR(64),
        FOREIGN KEY (id_user) REFERENCES users(id)
    )
""")

# Creation de la table Posts
cursor.execute("""CREATE TABLE IF NOT EXISTS Posts(
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        id_user INTEGER,
        creation DATETIME DEFAULT CURRENT_TIMESTAMP,
        titel VARCHAR(64),
        texte VARCHAR(1024)
    )
""")

