#!/usr/bin/python3

import cgi
import html
import sqlite3
import hashlib

from func.func import * 

base = sqlite3.connect ("data/database.sqlite3")
cursor = base.cursor ()

cursor.execute (r"""CREATE TABLE IF NOT EXISTS "users" (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                "admin" short,
                "user" varchar (64),
                "email" varchar (64),
                "password" varchar (64),
                dt datetime default current_timestamp
                );""")

form = cgi.FieldStorage()
if "user" in form and "email" in form and "pass" in form:
    user = form["user"].value
    email = form["email"].value
    
    pas = form["pass"].value
    pass_sh256 = hash_object = hashlib.sha256(pas.encode())

    cursor.execute("INSERT INTO users (user, email, password,admin) VALUES (?, ?, ?, ?);",(user, email, pass_sh256.hexdigest(),0))
    base.commit()
    redirect_to('index')
else:
    print(template_return("connextion"))